CREATE USER VACATION
IDENTIFIED BY VACATION
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO VACATION;
GRANT CREATE TABLE TO VACATION;
GRANT CREATE SEQUENCE TO VACATION;
GRANT CREATE VIEW TO VACATION;

ALTER USER vacation QUOTA UNLIMITED ON USERS;
CREATE TABLE VACATION_INFO (
ID                      DECIMAL(22)              PRIMARY KEY,
USER_ID                 VARCHAR2 (21)            NOT NULL,
TEAM_ID                 VARCHAR2 (21)            NOT NULL,
DATE_FROM               TIMESTAMP                NOT NULL,
DATE_TO                 TIMESTAMP                NOT NULL,
SUBSTITUTION_USER_IDS   VARCHAR2 (512),
COMMENT                 VARCHAR2 (512 CHAR),
IS_STATUS_CHANGED       NUMBER(1,0)              NOT NULL DEFAULT 0,
);
create SEQUENCE SEQ_VACATION_INFO START WITH 1 INCREMENT by 1;

CREATE TABLE VACATION_ADMIN (
USER_ID                 VARCHAR (21)        NOT NULL,
TEAM_ID                 VARCHAR (21)        NOT NULL,
CONSTRAINT VACATION_ADMIN_PK PRIMARY KEY (USER_ID)
);
-------------------------------------------------------------------------------
CREATE TABLE DUTY_LIST (
ID                      DECIMAL(22)          PRIMARY KEY,
TEAM_ID                 VARCHAR2 (21)        NOT NULL,
USER_GROUP_ID           VARCHAR2 (100)       UNIQUE NOT NULL,
CHANNEL_ID              VARCHAR2 (50)        UNIQUE NOT NULL,
MNEMONIC_NAME           VARCHAR2 (100)       NOT NULL,
LAST_MESSAGE_ID         VARCHAR2 (50),
);
CREATE SEQUENCE IF NOT EXISTS SEQ_DUTY_LIST START WITH 1 INCREMENT BY 1;

CREATE TABLE DUTY_USER (
ID                      DECIMAL(22)         PRIMARY KEY,
POSITION_ID             INTEGER,
USER_ID                 VARCHAR2 (21)       NOT NULL,
ON_DUTY                 NUMBER(1,0)         NOT NULL DEFAULT FALSE,
LAST_DATE_ON_DUTY       TIMESTAMP,
DUTY_LIST_ID            DECIMAL(22)         NOT NULL
);
ALTER TABLE DUTY_USER  ADD CONSTRAINT DUTY_LIST_FK
FOREIGN KEY (DUTY_LIST_ID) REFERENCES DUTY_LIST (ID);