INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS, COMMENT)
VALUES (0, 'USER0', 'TEAM0', '2018-06-16', '2018-06-18', 'USER1,USER2', 'COMMENT');

INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-1, 'USER0', 'TEAM1', '2019-01-07', '2019-01-21', 'USER1,USER2');
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-2, 'USER1', 'TEAM1', '2019-01-12', '2019-01-22', 'USER0,USER2');
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-3, 'USER1', 'TEAM1', '2019-01-10', '2019-01-13', 'USER0,USER2');

INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS, IS_STATUS_CHANGED)
VALUES (-4, 'USER1', 'TEAM2', '2020-02-08', '2020-02-13', 'USER0,USER2', FALSE);
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS, IS_STATUS_CHANGED)
VALUES (-5, 'USER2', 'TEAM2', '2020-02-10', '2020-02-13', 'USER0,USER2', TRUE);
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS, IS_STATUS_CHANGED)
VALUES (-6, 'USER3', 'TEAM2', '2020-02-10', '2020-02-13', 'USER0,USER2', FALSE);
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS, IS_STATUS_CHANGED)
VALUES (-7, 'USER3', 'TEAM2', '2020-02-14', '2020-02-15', 'USER0,USER2', FALSE);

INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-8, 'USER2', 'TEAM3', '2020-05-30', '2020-06-30', 'USER1,USER2');
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-9, 'USER2', 'TEAM4', '2020-06-30', '2020-07-30', 'USER1,USER2');
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-10, 'USER0', 'TEAM5', '2020-05-30', '2020-06-30', 'USER1,USER2');
INSERT INTO VACATION_INFO (ID, USER_ID, TEAM_ID, DATE_FROM, DATE_TO, SUBSTITUTION_USER_IDS)
VALUES (-11, 'USER2', 'TEAM5', '2020-06-30', '2020-07-30', 'USER1,USER2');

INSERT INTO VACATION_ADMIN (USER_ID, TEAM_ID) VALUES ('USER_ADMIN', 'TEAM0');
---------------------------------------------------------------------------------------------------------------
INSERT INTO DUTY_LIST (ID, TEAM_ID, USER_GROUP_ID, CHANNEL_ID, MNEMONIC_NAME)
VALUES (0, 'TEAM0', 'GROUP0', 'CHANNEL0', 'MNEMONIC0');
INSERT INTO DUTY_LIST (ID, TEAM_ID, USER_GROUP_ID, CHANNEL_ID, MNEMONIC_NAME)
VALUES (1, 'TEAM3', 'GROUP3', 'CHANNEL3', 'MNEMONIC3');
INSERT INTO DUTY_LIST (ID, TEAM_ID, USER_GROUP_ID, CHANNEL_ID, MNEMONIC_NAME)
VALUES (2, 'TEAM4', 'GROUP4', 'CHANNEL4', 'MNEMONIC4');
INSERT INTO DUTY_LIST (ID, TEAM_ID, USER_GROUP_ID, CHANNEL_ID, MNEMONIC_NAME)
VALUES (3, 'TEAM5', 'GROUP5', 'CHANNEL5', 'MNEMONIC5');

INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (0, 0, 'USER0', TRUE, '2020-06-25', 0);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (1, 1, 'USER1', FALSE , '2020-06-26', 0);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (2, 2, 'USER2', FALSE , '2020-06-27', 0);

INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (3, 0, 'USER0', FALSE, '2020-06-25', 1);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (4, 1, 'USER1', TRUE , '2020-06-26', 1);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (5, 2, 'USER2', FALSE , '2020-06-27', 1);

INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (6, 0, 'USER0', FALSE, '2020-06-25', 2);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (7, 1, 'USER1', TRUE , '2020-06-26', 2);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (8, 2, 'USER2', FALSE , '2020-06-27', 2);

INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (9, 0, 'USER0', FALSE, '2020-06-25', 3);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (10, 1, 'USER1', TRUE , '2020-06-26', 3);
INSERT INTO DUTY_USER (ID, POSITION_ID, USER_ID, ON_DUTY, LAST_DATE_ON_DUTY, DUTY_LIST_ID)
VALUES (11, 2, 'USER2', FALSE , '2020-06-27', 3);